apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: minikubes.alexellis.io
spec:
  group: alexellis.io
  names:
    kind: Minikube
    listKind: MinikubeList
    plural: minikubes
    singular: minikube
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v2alpha1
  versions:
  - name: v2alpha1
    served: true
    storage: true
