apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-operator
  namespace: clusters
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minikube-operator
  template:
    metadata:
      labels:
        name: minikube-operator
    spec:
      serviceAccountName: minikube-operator
      containers:
        - name: minikube-operator
          # Replace this with the built image name
          image: alexellis2/minikube-operator:0.1.2
          command:
          - minikube-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "minikube-operator"
