kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minikube-operator
  namespace: clusters
subjects:
- kind: ServiceAccount
  name: minikube-operator
roleRef:
  kind: Role
  name: minikube-operator
  apiGroup: rbac.authorization.k8s.io
